/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/kavis/.choosenim/toolchains/nim-0.18.0/lib -o /home/kavis/Documents/Project/Euler/Nim/nimcache/p002.o /home/kavis/Documents/Project/Euler/Nim/nimcache/p002.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
N_LIB_PRIVATE N_NIMCALL(void, main_K3g0QKuQvcH9a9as7e27DIqg)(void);
N_LIB_PRIVATE N_NIMCALL(NI, fib_SgcJbvgmux9bfmpfxWiWgLA)(NI l);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, p002DatInit000)(void);
NIM_CONST tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ TM_YTy13f7TM2gSI9c9cC7D8tUw_2 = {((NI) 1),
((NI) 1)}
;

N_LIB_PRIVATE N_NIMCALL(NI, fib_SgcJbvgmux9bfmpfxWiWgLA)(NI l) {
	NI result;
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ a;
{	result = (NI)0;
	a = TM_YTy13f7TM2gSI9c9cC7D8tUw_2;
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 1);
		{
			while (1) {
				tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ _;
				if (!(res <= l)) goto LA3;
				i = res;
				_.Field0 = a.Field1;
				_.Field1 = (NI)(a.Field0 + a.Field1);
				a.Field0 = _.Field0;
				a.Field1 = _.Field1;
				res += ((NI) 1);
			} LA3: ;
		}
	}
	result = a.Field0;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, main_K3g0QKuQvcH9a9as7e27DIqg)(void) {
	NI s;
	NI l;
	tyArray_nHXaesL0DJZHyVS07ARPRA T10_;
	s = ((NI) 0);
	l = ((NI) 1);
	{
		while (1) {
			NI T3_;
			T3_ = (NI)0;
			T3_ = fib_SgcJbvgmux9bfmpfxWiWgLA(l);
			if (!(T3_ < ((NI) 4000000))) goto LA2;
			{
				NI T6_;
				NI T9_;
				T6_ = (NI)0;
				T6_ = fib_SgcJbvgmux9bfmpfxWiWgLA(l);
				if (!((NI)(T6_ % ((NI) 2)) == ((NI) 0))) goto LA7_;
				T9_ = (NI)0;
				T9_ = fib_SgcJbvgmux9bfmpfxWiWgLA(l);
				s += T9_;
			}
			LA7_: ;
			l += ((NI) 1);
		} LA2: ;
	}
	memset((void*)T10_, 0, sizeof(T10_));
	T10_[0] = nimIntToStr(s);
	echoBinSafe(T10_, 1);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_futureDatInit000();
	p002DatInit000();
	stdlib_macrosInit000();
	stdlib_sequtilsInit000();
	stdlib_mathInit000();
	stdlib_futureInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	{
		if (!NIM_TRUE) goto LA3_;
		main_K3g0QKuQvcH9a9as7e27DIqg();
	}
	LA3_: ;
}

NIM_EXTERNC N_NOINLINE(void, p002DatInit000)(void) {
}

